config/routes.rb
Rails.application.routes.draw do
  
  get '/' => 'welcome#home'
  get '/about' => 'welcome#about'
  get '/surgeons' => 'welcome#surgeons'
  get '/before' => 'welcome#before'
  get '/after' => 'welcome#after'
  
  root 'welcome#home'
  
  namespace :employees do
    root 'employees#home'
    
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def about
  end

  def surgeons
  end
  
  def before
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rhsc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div class="container">  
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("Red Hills Logo.jpg", class: "navbar-brand", style: "width: 100px"), root_path %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">About <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About Us", about_path %></li>
            <li><%= link_to "Surgeons", surgeons_path %></li>
          </ul>
        </li>
        <li><%= link_to "Before Surgery", before_path %></li>
        <li><%= link_to "After Surgery", after_path %></li>
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  
  


<%= yield %>
</div>
</body>
</html>

app/views/welcome/about.html.erb
<h1>This is the about Page</h1>
<p>This is where we are going to talk about how great our center is!</p>

app/views/welcome/after.html.erb
<h1>This is the after surgery page!</h1>
<p>This is where we are going to talk about what patients need to know after surgery. Topics such as dont call us about your bleeding, we dont set your follow-up, what to do when they lose their post-op instructions, etc.</p>

app/views/welcome/before.html.erb
<h1>This is the before surgery page!</h1>
<p>This is where we talk about what the patients need to know about before they have surgery. This will include OMP, not eating, what to bring etc.</p>

app/views/welcome/home.html.erb
<h3 class="text-center">Welcome to Red Hills Surgical Center</h3>

<div id="homepage-carousel" class="carousel slide hidden-xs" data-ride="carousel" style="width: 750px; margin: 0 auto">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#homepage-carousel" data-slide-to="0" class="active"></li>
    <li data-target="#homepage-carousel" data-slide-to="1"></li>
    <li data-target="#homepage-carousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag("front_shot.jpg", class: "img-responsive center-block") %>
    </div>
    <div class="item">
      <%= image_tag("preop_beds.jpg", class: "img-responsive center-block") %>
    </div>
    <div class="item">
      <%= image_tag("or_table.jpg", class: "img-responsive center-block") %>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#homepage-carousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#homepage-carousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<hr>

<p>Red Hills Surgical Center is a state of the art, multi-specialty facility dedicated to providing compassionate, leading edge, patient-centered health care for all.  We pursue perfection in a trusting and learning environment, thus enhancing the quality of life of those we serve.  We are dedicated to the safety, comfort and privacy of our patients.</p>

<p>Red Hills boasts a pleasant aesthetic environment in a 17,000 plus square foot single story building.  We provide a covered front entrance patient drop off area, covered rear pick up area and ample free parking.</p>

<p>Our physicians and staff are dedicated to healthcare excellence and high quality service.  We are fully accredited through The Accrediting Association for Ambulatory Health Care (AAAHC) - which means we measure the quality of our services and performance against nationally-recognized standards.</p>

<div class="row">
  <div class="col-md-4">
    <a href="https://www.patientnotebook.com/redhillssurgicalcenter/payment" class="btn btn-danger">Pay Your Bill</a>
  </div>
</div>

app/views/welcome/surgeons.html.erb
<h1>This is the Surgeons Page</h1>
<p>This is where we are going to talk about our wonderful surgeons</p>